# Generated by Django 4.0.4 on 2022-09-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoring_course', '0026_chapter_parent'),
        ('authoring_core', '0002_auto_20211122_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Questionnaire', max_length=255)),
                ('title_en', models.CharField(default='Questionnaire', max_length=255, null=True)),
                ('title_de', models.CharField(default='Questionnaire', max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_course', to='authoring_course.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_creator', to='authoring_core.organizationmembership')),
            ],
        ),
    ]
