# Generated by Django 4.0.4 on 2022-10-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0002_alter_asset_file'),
        ('authoring_core', '0002_auto_20211122_1118'),
        ('authoring_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='authoring_core.organizationmembership')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='authoring_questionnaire.questionnaire')),
            ],
        ),
    ]
