# Generated by Django 4.0.4 on 2022-10-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0002_alter_asset_file'),
        ('authoring_questionnaire', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asset_de',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='question',
            name='asset_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
