# Generated by Django 4.0.4 on 2022-11-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_questionnaire', '0004_alter_questionnaire_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authoring_questionnaire.question')),
            ],
            bases=('authoring_questionnaire.question',),
        ),
    ]
