# Generated by Django 4.0.4 on 2022-11-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_questionnaire', '0005_multiplechoicequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asset_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asset_en',
        ),
    ]
