# Generated by Django 4.0.4 on 2022-11-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0002_alter_asset_file'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('authoring_core', '0002_auto_20211122_1118'),
        ('authoring_questionnaire', '0006_remove_question_asset_de_remove_question_asset_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_option', to='smartstudy_assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_answer_options', to='authoring_core.organizationmembership')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='authoring_questionnaire.question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authoring_questionnaire.answeroption')),
                ('correct_choice', models.BooleanField()),
                ('order_index', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('authoring_questionnaire.answeroption',),
        ),
        migrations.CreateModel(
            name='TextAnswerOption',
            fields=[
                ('answeroption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authoring_questionnaire.answeroption')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('authoring_questionnaire.answeroption',),
        ),
    ]
