# Generated by Django 4.0.4 on 2023-01-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0027_remove_exam_course_remove_exam_created_by_and_more'),
        ('authoring_questionnaire', '0007_answeroption_multiplechoiceansweroption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='chapter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='authoring_course.chapter'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='authoring_course.course'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('chapter', None), ('course__isnull', False)), models.Q(('chapter__isnull', False), ('course', None)), _connector='OR'), name='course_or_chapter_required'),
        ),
    ]
