# Generated by Django 4.0.4 on 2023-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_questionnaire', '0010_question_external_id_question_last_synchronized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='external_id',
            field=models.BigIntegerField(blank=True, help_text='Specifies the id on the remote server', null=True),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='last_synchronized',
            field=models.DateTimeField(help_text='The last synchronization date for this model', null=True),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='synchronization_policy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Synchronize on every save'), (2, 'Synchronize on every save, async'), (3, 'Synchronize only on external trigger')], default=1, help_text='Defines the synchronization policy for this model'),
        ),
    ]
