# Generated by Django 4.0.4 on 2023-04-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_questionnaire', '0011_answeroption_external_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswerOption',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TextAnswerOption',
        ),
    ]
