# Generated by Django 4.0.4 on 2023-04-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0002_alter_asset_file'),
        ('authoring_core', '0002_auto_20211122_1118'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('authoring_questionnaire', '0012_remove_multiplechoiceansweroption_answeroption_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime of this model')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Last modification datetime of this model')),
                ('external_id', models.BigIntegerField(blank=True, help_text='Specifies the id on the remote server', null=True)),
                ('last_synchronized', models.DateTimeField(help_text='The last synchronization date for this model', null=True)),
                ('synchronization_policy', models.PositiveSmallIntegerField(choices=[(1, 'Synchronize on every save'), (2, 'Synchronize on every save, async'), (3, 'Synchronize only on external trigger')], default=1, help_text='Defines the synchronization policy for this model')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset')),
                ('created_by', models.ForeignKey(help_text='The creator of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership')),
                ('modified_by', models.ForeignKey(help_text='The last modifier of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='authoring_questionnaire.questionnaire')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authoring_questionnaire.question')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('authoring_questionnaire.question',),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation datetime of this model')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Last modification datetime of this model')),
                ('external_id', models.BigIntegerField(blank=True, help_text='Specifies the id on the remote server', null=True)),
                ('last_synchronized', models.DateTimeField(help_text='The last synchronization date for this model', null=True)),
                ('synchronization_policy', models.PositiveSmallIntegerField(choices=[(1, 'Synchronize on every save'), (2, 'Synchronize on every save, async'), (3, 'Synchronize only on external trigger')], default=1, help_text='Defines the synchronization policy for this model')),
                ('text', models.TextField(blank=True)),
                ('correct_answer', models.BooleanField(default=False)),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_option', to='smartstudy_assets.asset')),
                ('created_by', models.ForeignKey(help_text='The creator of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership')),
                ('modified_by', models.ForeignKey(help_text='The last modifier of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='authoring_questionnaire.choicequestion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
