# Generated by Django 4.0.4 on 2023-05-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_questionnaire', '0013_question_choicequestion_answeroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='title_en',
        ),
    ]
