# Generated by Django 4.0.4 on 2023-05-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0037_courseintent_chapter'),
        ('authoring_questionnaire', '0015_remove_questionnaire_course_or_chapter_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='authoring_course.course'),
            preserve_default=False,
        ),
    ]
