# Generated by Django 4.0.4 on 2023-05-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0038_alter_courseintent_chapter'),
        ('authoring_questionnaire', '0016_alter_questionnaire_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='chapter',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='authoring_course.chapter'),
        ),
    ]
