# Generated by Django 4.0.4 on 2023-04-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_intent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intent',
        ),
    ]
