version: "3.8"

services:
  vision-duckling:
    image: rasa/duckling:0.1.6.5-r4
    container_name: vision-duckling
    ports:
      - "8008:8000"    
    networks:
      - my-custom-network

  vision-chatbot-agent:
    depends_on:
      - vision-duckling
    build:
      context: ./
      dockerfile: docker/chatbot_agent_dockerfile
    container_name: vision-chatbot-agent
    environment:
      - URL_ACTION_ENDPOINT=${ACTION_ENDPOINT_URL-https://botactions.visionapp.smart-study.net}
    volumes:
      - ./chatbot:/app
      - ./config:/config
      - ./docker/agent:/develop
    ports:
      - "5005:5005"
    networks:
      - my-custom-network

  vision-chatbot-actions:
    depends_on:
      - vision-chatbot-agent
    build:
      context: ./
      dockerfile: docker/chatbot_actions_dockerfile
    container_name: vision-chatbot-actions
    environment:
      - URL_ACTION_ENDPOINT=${ACTION_ENDPOINT_URL-https://botactions.visionapp.smart-study.net}
    volumes:
      - ./chatbot:/app
      - ./config:/config
      - ./docker/actions:/develop
    ports:
      - "5055:5055"
    networks:
      - my-custom-network      

  vision-frontend:
    build:
      context: ./
      dockerfile: docker/chatbot_frontend_dockerfile
    container_name: vision-frontend
    volumes:
      - ./app:/app
      - ./config:/config
      - ./docker/frontend:/develop
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks: 
      - my-custom-network

  vision-client:
    build:
      context: ./
      dockerfile: docker/chatbot_client_dockerfile
    container_name: vision-client
    volumes:
      - ./client:/app
      - ./docker/client:/develop
    ports:
      - "8080:8080"
    networks:
      - my-custom-network

  scormviewer:
    build:
      context: ./
      dockerfile: docker/chatbot_scormviewer_dockerfile
    container_name: scormviewer
    volumes:
      - ./scormviewer/app:/app
      - ./docker/scormviewer:/develop
      - ./scormviewer/share:/share
    ports:
      - "5001:5001"
    networks:
      - my-custom-network

  backend:
    build:
      context: ./backend
      dockerfile: docker/django_dockerfile
    container_name: backend
    environment:
      - URL_BACKEND=https://${BACKEND_URL}
      - URL_FRONTEND=https://${FRONTEND_URL}
      - URL_CHATBOT_AGENT=${URL_CHATBOT_AGENT}
      - ACTIVE_BOTAPI_URL=${ACTIVE_BOTAPI_URL}
      - USE_X_FORWARDED_HOST=${BACKEND_USE_X_FORWARD-True}
      - DEBUG=${BACKEND_DEBUG-False}
      - SECRET_KEY=AVERYUNSAFEKEY
    volumes:
      - ./config:/backend/config
      - ./files:/backend/files
      - ./db:/backend/database
      - ../share:/backend/share
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-custom-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/frontend_dockerfile
    container_name: authoring-frontend
    environment:
      - PRODUCTION=${FRONTEND_PRODUCTION-true}
      - API_URL=https://${BACKEND_URL:?FQDN (e.g. api.visionapp.smart-study.net)}/v1
      - NGINX_PORT=${FRONTEND_NGINX_PORT-9000}
    ports:
      - "${FRONTEND_NGINX_PORT-9000}:${FRONTEND_NGINX_PORT-9000}"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge