# Generated by Django 3.2.6 on 2021-10-04 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringinvite',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='authoringinvite',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoringinvite',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='authoringinvite',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authoringinvite',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.SMART_STUDY_AUTH_PERSON_MODEL),
        ),
        migrations.AddField(
            model_name='authoringinvite',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authoringperson',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='authoringperson',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='authoringperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='authoringinvite',
            constraint=models.CheckConstraint(check=models.Q(('email', ''), _negated=True), name='invite_email_not_empty'),
        ),
    ]
