# Generated by Django 3.2.6 on 2021-10-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.SMART_STUDY_AUTH_PERSON_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default='')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring_core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.SMART_STUDY_AUTH_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Department'), (1, 'Group')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnitRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modifiable', models.BooleanField(default=True)),
                ('defaultId', models.SmallIntegerField(default=0)),
                ('can_modify_organization_unit_details', models.BooleanField(default=False)),
                ('can_modify_organization_unit_roles', models.BooleanField(default=False)),
                ('can_modify_organization_unit_members', models.BooleanField(default=False)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authoring_core.organizationunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring_core.organizationmembership')),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoring_core.organizationunit')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='authoring_core.organizationunitrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='members',
            field=models.ManyToManyField(related_name='organization_unit_memberships', through='authoring_core.OrganizationUnitMembership', to='authoring_core.OrganizationMembership'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='authoring_core.organization'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='authoring_core.organizationunit'),
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modifiable', models.BooleanField(default=True)),
                ('defaultId', models.SmallIntegerField(default=0)),
                ('can_modify_organization_details', models.BooleanField(default=False)),
                ('can_modify_organization_roles', models.BooleanField(default=False)),
                ('can_modify_organization_members', models.BooleanField(default=False)),
                ('can_modify_organization_unit_details', models.BooleanField(default=False)),
                ('can_modify_organization_unit_roles', models.BooleanField(default=False)),
                ('can_modify_organization_unit_members', models.BooleanField(default=False)),
                ('can_manage_courses', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authoring_core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='authoring_core.organizationrole'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_owner', to='authoring_core.organizationmembership'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='authoring_core.OrganizationMembership', to=settings.SMART_STUDY_AUTH_PERSON_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationunitrole',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='organization_unit_role_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='organization_role_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='name_not_empty'),
        ),
    ]
