# Generated by Django 3.2.6 on 2021-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationunitrole',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationunitrole',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
