# Generated by Django 3.2.6 on 2021-12-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_core', '0002_auto_20211122_1118'),
        ('authoring_course', '0003_subchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slides', to='authoring_core.organizationmembership')),
                ('sub_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chapters', to='authoring_course.subchapter')),
            ],
        ),
    ]
