# Generated by Django 3.2.6 on 2022-01-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0004_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='sub_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='authoring_course.subchapter'),
        ),
    ]
