# Generated by Django 3.2.6 on 2022-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0009_merge_0007_exam_0008_alter_course_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
