# Generated by Django 3.2.6 on 2022-01-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0010_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartstudy_assets.asset'),
        ),
    ]
