# Generated by Django 3.2.6 on 2022-01-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0010_course_image'),
        ('authoring_course', '0011_alter_question_asset'),
    ]

    operations = [
    ]
