# Generated by Django 3.2.6 on 2022-01-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0012_merge_0010_course_image_0011_alter_question_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartstudy_assets.asset'),
        ),
    ]
