# Generated by Django 3.2.6 on 2022-01-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0014_answerchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='asset_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='asset_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='asset_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='question',
            name='asset_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartstudy_assets.asset'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
