# Generated by Django 3.2.6 on 2022-01-19 13:09

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0015_auto_20220117_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='content',
        ),
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartstudy_assets.asset'),
        ),
    ]
