# Generated by Django 3.2.6 on 2022-01-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0016_remove_slide_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='smartstudy_assets.asset'),
        ),
    ]
