# Generated by Django 3.2.6 on 2022-01-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0017_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='smartstudy_assets.asset'),
        ),
    ]
