# Generated by Django 3.2.6 on 2022-01-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartstudy_assets', '0001_initial'),
        ('authoring_course', '0018_alter_slide_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asset_de',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asset_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='smartstudy_assets.asset'),
        ),
    ]
