# Generated by Django 3.2.6 on 2022-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0020_auto_20220125_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='Exam', max_length=255),
        ),
    ]
