# Generated by Django 3.2.6 on 2022-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0021_auto_20220207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
