# Generated by Django 3.2.6 on 2022-02-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0023_auto_20220221_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='authoring_course.chapter'),
        ),
    ]
