# Generated by Django 3.2.6 on 2022-02-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0024_alter_slide_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubChapter',
        ),
    ]
