# Generated by Django 3.2.6 on 2022-02-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0025_delete_subchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='authoring_course.chapter'),
        ),
    ]
