# Generated by Django 4.0.4 on 2022-10-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0026_chapter_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asset_de',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asset_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
