# Generated by Django 4.0.4 on 2023-02-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0027_remove_exam_course_remove_exam_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_begin_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ressources',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
