# Generated by Django 4.0.4 on 2023-03-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0029_alter_course_materials_alter_course_ressources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.BigIntegerField(blank=True, help_text='Specifies the id on the remote server', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_synchronized',
            field=models.DateTimeField(help_text='The last synchronization date for this model', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modified_by',
            field=models.ForeignKey(help_text='The last modifier of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership'),
        ),
        migrations.AddField(
            model_name='course',
            name='synchronization_policy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Synchronize on every save'), (2, 'Synchronize on every save, async'), (3, 'Synchronize only on external trigger')], default=1, help_text='Defines the synchronization policy for this model'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation datetime of this model'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(help_text='The creator of this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authoring_core.organizationmembership'),
        ),
        migrations.AlterField(
            model_name='course',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification datetime of this model'),
        ),
    ]
