# Generated by Django 4.0.4 on 2023-04-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0031_courseintent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseintent',
            old_name='course_id',
            new_name='course',
        ),
    ]
