# Generated by Django 4.0.4 on 2023-04-17 07:21

from django.db import migrations, models

def initialize_chapters(apps, schema_editor):
    Course = apps.get_model('authoring_course', 'Course')
    Chapter = apps.get_model('authoring_course', 'Chapter')

    for c in Course.objects.all():
        for order, chapter in enumerate(Chapter.objects.filter(course=c)):
            chapter.order = order
            chapter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0033_chapter_external_id_chapter_last_synchronized_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),

        migrations.RunPython(initialize_chapters, migrations.RunPython.noop),
    ]
