# Generated by Django 4.0.4 on 2023-05-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0034_alter_chapter_options_chapter_order'),
        ('authoring_course', '0034_courseexam'),
    ]

    operations = [
    ]
