# Generated by Django 4.0.4 on 2023-05-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0036_merge_20230509_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseintent',
            name='chapter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='authoring_course.chapter'),
        ),
    ]
