# Generated by Django 4.0.4 on 2023-05-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0036_coursetask'),
        ('authoring_course', '0038_alter_courseintent_chapter'),
    ]

    operations = [
    ]
