# Generated by Django 4.0.4 on 2023-05-23 17:21

from django.db import migrations, models

def initialize_slide_order(apps, schema_editor):
    Chapter = apps.get_model('authoring_course', 'Chapter')
    Slide = apps.get_model('authoring_course', 'Slide')

    for c in Chapter.objects.all():
        for order, slide in enumerate(Slide.objects.filter(chapter=c)):
            slide.order = order
            slide.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_course', '0039_merge_0036_coursetask_0038_alter_courseintent_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),

        migrations.RunPython(initialize_slide_order, migrations.RunPython.noop),
    ]
